spring:
  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:example}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 0
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false 

application:
  cors:
    allowed: "*"
    time: 3600
 
influx:
  url: ${INFLUX_URL}
  token: ${INFLUX_TOKEN}
  org: ${INFLUX_ORG}
  bucket: ${INFLUX_BUCKET}
    
mqtt:
  url: ${MQTT_URL}
    